// atomic-docs.config.js
// This file was automatically generated by vue-atomic-docs
// You can modify this file to customize your documentation setup

module.exports = {
  // Path to output the atomic-docs-manifest.ts file
  output: 'src/atomic-docs-manifest.ts',
  
  // Path to the components directory
  componentsDir: 'src/components',
  
  // Path to the examples directory
  examplesDir: 'src/component-examples',
  
  // Base name for components in the plugin
  pluginComponentsBaseName: 'components',
  
  // Base name for examples in the plugin
  pluginExamplesBaseName: 'component-examples'
};
