// scripts/create-config.js
/**
 * This script creates a default atomic-docs.config.js file in the root of the consuming app
 * if it doesn't already exist.
 */
const fs = require('fs');
const path = require('path');

// Get the root directory of the consuming app
// INIT_CWD is set by npm and points to the directory where npm was invoked
// Fallback to process.cwd() if INIT_CWD is not available
const appRoot = process.env.INIT_CWD || process.cwd();

console.log(`Creating config file in app root: ${appRoot}`);

// Path to the config file
const configPath = path.join(appRoot, 'atomic-docs.config.js');

// Default config content
const defaultConfigContent = `// atomic-docs.config.js
// This file was automatically generated by vue-atomic-docs
// You can modify this file to customize your documentation setup

module.exports = {
  // Path to output the atomic-docs-manifest.ts file
  output: 'src/atomic-docs-manifest.ts',

  // Path to the components directory
  componentsDir: 'src/components',

  // Path to the examples directory
  examplesDir: 'src/component-examples',

  // Base name for components in the plugin
  pluginComponentsBaseName: 'components',

  // Base name for examples in the plugin
  pluginExamplesBaseName: 'component-examples'
};
`;

// Check if the config file already exists
if (fs.existsSync(configPath)) {
  console.log(`Config file already exists at ${configPath}`);
} else {
  try {
    // Create the config file
    fs.writeFileSync(configPath, defaultConfigContent);
    console.log(`✅ Created default config file at ${configPath}`);
  } catch (error) {
    console.error(`❌ Error creating config file: ${error.message}`);
  }
}
