// This is a placeholder file for build purposes only.
// The actual file will be generated by the consuming application.
import type { ComponentItem, ExampleItem } from './types';

export const components: ComponentItem[] = [];
export const exampleComponents: ExampleItem[] = [];

export const componentModules: Record<string, () => Promise<any>> = {};
export const rawComponentSourceModules: Record<string, () => Promise<string>> = {};
export const exampleModules: Record<string, () => Promise<any>> = {};