
// This file is auto-generated by scripts/generate-docs-manifest.js
// Do not edit this file directly.

import type { ComponentItem, ExampleItem } from './types';

export const components: ComponentItem[] = [];

export const exampleComponents: ExampleItem[] = [];
